<a href="https://colab.research.google.com/github/JosegregTovar/GOOGLE-COLLAB/blob/main/Copia_de_Actividad3BDManipulacion_A01840476.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MAESTRÍA EN INTELIGENCIA ARTIFICIAL APLICADA**

**Curso: TC5053 - Ciencia y analítica de datos**

Tecnológico de Monterrey

Prof Grettel Barceló Alonso

**Semana 3**
Bases, almacenes y manipulación de datos

---

*   NOMBRE: JOSEGREG DE JESUS TOVAR BLANCO
*   MATRÍCULA: A01840476

---

En esta actividad usarás una base de datos relacional basada en el informe de participación y la lista del top 10 de Netflix. Incluye películas y programas de televisión, así como información sobre temporadas, métricas de visualización, fechas de estreno, duración y más, organizada en las siguientes tablas:

* `movie`: Información general de las películas.

* `tv_show`: Información general de los programas de televisión.

* `season`: Datos de las temporadas asociadas a cada programa de TV.

* `view_summary`: Métricas de visualización y rendimiento de películas o temporadas.

Revisa con detalle su esquema para que comprendas cómo se relacionan las tablas anteriores.

**NOTA IMPORTANTE:** Asegúrate de responder *explícitamente* todos los cuestionamientos.

`PyMySQL` es una librería escrita en Python puro que funciona como conector (*driver*) para motores de bases de datos MySQL, permitiendo abrir conexiones, ejecutar consultas SQL y recuperar resultados directamente desde programas en Python.

In [1]:
pip install pymysql

Requirement already satisfied: pymysql in /usr/local/lib/python3.12/dist-packages (1.1.2)

`SQLAlchemy` es una librería de Python que facilita la interacción con bases de datos y permite mantener un pool de conexiones eficiente, gestionar *commits* y *rollbacks* de forma automática y asegurar que múltiples conexiones simultáneas se manejen de manera segura, incluso cuando se ejecutan consultas SQL “puras”

In [2]:
# Importa las librerías necesarias
import pymysql
import sqlalchemy as sqla
import pandas as pd

Se crea una conexión (`conn`) para luego invocar declaraciones SQL.

In [13]:
# motor+driver://usuarioBD:clave@ipHostDBMS:puerto/esquema
# pool_recycle controla el tiempo máximo de vida de una conexión en el pool (3600 segundos = 1 hora)
db = sqla.create_engine('mysql+pymysql://mnaTC4029User:mnaTC4029Pass!@172.208.104.202:3306/Netflix', pool_recycle=3600)
conn = db.connect()

def run_query(sql: str) -> pd.DataFrame:
    """Ejecuta SQL y devuelve DataFrame."""
    return pd.read_sql(sqla.text(sql), conn)

1.	Extrae toda la información de las películas que duran más de 5 horas.

Para que tus consultas sean más legibles y fáciles de mantener, puedes usar este formato multilínea con comillas triples y `sqla.text()`. Por ejemplo:

```
q1 = sqla.text("""
  SELECT*
  FROM movie
  WHERE runtime > 300
""")
pd.read_sql(query, conn)
```

In [15]:
conn.rollback()
q1 = """
SELECT*
FROM movie
WHERE runtime > 300
"""
df_q1 = run_query(q1)
df_q1.head()

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
0,5793,2024-01-01,2024-01-01,b'\x00',None,日本統一シリーズ: 映画シリーズ,None,3892,Nihontouitsu Series: Film Series
1,5794,2024-01-01,2024-01-01,b'\x00',None,釣りバカ日誌: 映画シリーズ,None,2120,Free and Easy Series: Film Series
2,5874,2024-01-01,2024-01-01,b'\x01',None,None,2021-08-06,312,Navarasa: Limited Series
3,9729,2024-01-01,2024-01-01,b'\x00',None,織田同志会 織田征仁: 映画シリーズ,None,710,Seiji Oda: Film Series
4,9730,2024-01-01,2024-01-01,b'\x00',None,キングダム～首領になった男～: 映画シリーズ,None,427,Kingdom ~ The Man Who Became the Top ~: Film S...

2.	¿Cuál es el porcentaje de películas disponibles únicamente en EU en relación con el total, excluyendo los valores `NULL`? La consulta SQL debe entregar directamente el porcentaje final. No se deben devolver resultados parciales para realizar el cálculo en Python.

In [23]:
conn.rollback()
q2 = """
SELECT
  100.0 *
  SUM(CASE WHEN
   available_globally = 0 THEN 1
   ELSE 0 END)
        / COUNT(available_globally) AS Solo_en_USA
FROM movie
WHERE available_globally IS NOT NULL
"""
df_q2 = run_query(q2)
df_q2

   Solo_en_USA
0     83.57175

3.	¿Cuáles son los idiomas o regiones originales en la tabla de películas?
* ¿Cuántos registros tienen el campo `locale` con valor `NULL`? (NULL en SQL ⇔ None en Python)

In [28]:
conn.rollback()
q3a = """
SELECT DISTINCT
  locale
FROM movie
ORDER BY locale
;
"""
df_q3a = run_query(q3a)

q3b = """
SELECT
  COUNT(*) AS Conteo_Registros_Null_locale
FROM movie
WHERE locale IS NULL
;
"""
df_q3b = run_query(q3b)

print("Locales distintos:")
display(df_q3a)

print("\nCantidad de locale NULL:")
display(df_q3b)

Locales distintos:

  locale
0   None
1     en

Cantidad de locale NULL:

   Conteo_Registros_Null_locale
0                         11255

4.	Asumiendo que los valores `NULL` en `locale` corresponden a otro idioma (diferente del inglés), el título original de la película NO debería coincidir con el título principal en dichos registros.
* Determina cuántas películas tienen títulos diferentes en estos dos campos (`title` y `original_title`).
*  ¿Coinciden los resultados (cantidad de `NULL` y títulos diferentes)? Si no es así, identifica qué características tienen los registros restantes.
* Finalmente, concluye si la suposición de que los valores `NULL` en `locale` indican que la película está en otro idioma es válida.

In [32]:
# 4.a ¿Cuántas con locale NULL?

df_q4a = df_q3b

# 4.b ¿Cuántas con locale NULL y titles diferentes?
q4b = """
SELECT
  COUNT(*) AS Registros_title_original_title_diferentes
FROM movie
WHERE locale IS NULL
  AND title <> original_title
;
"""
df_q4b = run_query(q4b)

display(df_q4a)
display(df_q4b)

   Conteo_Registros_Null_locale
0                         11255

   Registros_title_original_title_diferentes
0                                       3947

In [34]:
#Como no coinciden toca reaponder:
# 4.c ¿Cuántas con locale NULL y titles iguales? (los "restantes")
q4c = """
SELECT
  COUNT(*) AS Registros_title_original_title_iguales
FROM movie
WHERE locale IS NULL
  AND title = original_title
;
"""
df_q4c = run_query(q4c)
display(df_q4c)

   Registros_title_original_title_iguales
0                                      17

In [37]:
#Hay que ver cuales son, pero intuyo que son peliculas de paises de habla inglesa:
# 4.d Traer ejemplos de esos "restantes" para inspección

q4d = """
SELECT
  id, title, original_title, locale, available_globally, release_date, runtime
FROM movie
WHERE locale IS NULL
  AND title = original_title
LIMIT 50
;
"""
df_q4d = run_query(q4d)

display(df_q4d)

,id,title,original_title,locale,available_globally,release_date,runtime
0,1089,Recep Ivedik 7,Recep İvedik 7,None,b'\x00',None,133
1,1349,Veronica,Verónica,None,b'\x00',None,105
2,3509,Fantomas,Fantômas,None,b'\x00',None,100
3,3611,Luccas Neto em: O Hotel Magico,Luccas Neto em: O Hotel Mágico,None,b'\x00',None,70
4,4566,Un Dia En El Paraiso,Un día en el paraíso,None,b'\x00',None,97
5,5077,Superlopez,Superlópez,None,b'\x01',None,108
6,5211,Baris Akarsu Merhaba,Barış Akarsu Merhaba,None,b'\x00',None,115
7,5684,Totem,Tótem,None,b'\x00',None,95
8,6427,La Pena Maxima,La pena máxima,None,b'\x01',None,89
9,6530,Mirciulica,Mirciulică,None,b'\x00',None,92
10,7205,Animas,Ánimas,None,b'\x00',2019-01-25,87
11,7519,Dejame Vivir,Déjame Vivir,None,b'\x00',None,62
12,7726,Gangster Ka: African,Gangster Ka: Afričan,None,b'\x00',None,97
13,8459,Party Hard,Párty Hárd,None,b'\x00',None,62
14,10358,Extasis,Éxtasis,None,b'\x00',None,88
15,10592,Malefique,Maléfique,None,b'\x00',None,86
16,11031,Tiramisu,Tiramisù,None,b'\x00',None,92

**Conclusión:**
Viendo realmente lo que ocurrió es que toma que son iguales porque toma caracteres Especiales como acentos u otros y los hace iguales, se tendría que acotar para que los haga totalmente diferentes y asi comparar peras con peras.

El campo NULL en Locale **SI** indica que la pelicula está en otro Idioma.

5.	Determina el título de la película que ha permanecido más tiempo en el top 10.

In [40]:
conn.rollback()
q5 = """
SELECT
  m.title,
  MAX(vs.cumulative_weeks_in_top10) AS Tiempo_en_Top10
FROM view_summary vs
JOIN movie m
  ON m.id = vs.movie_id
GROUP BY m.title
ORDER BY Tiempo_en_Top10 DESC
LIMIT 1
;
"""
df_q5 = run_query(q5)

display(df_q5)

           title  Tiempo_en_Top10
0  The Boss Baby               22

6.	Identifica los 5 programas de TV con mayor cantidad de temporadas.

In [42]:
q6 = """
SELECT
  ts.title AS Programa_de_TV,
  COUNT(s.id) AS Temporadas
FROM tv_show ts
JOIN season s
  ON s.tv_show_id = ts.id
GROUP BY ts.title
ORDER BY Temporadas DESC
LIMIT 5
;
"""
df_q6 = run_query(q6)
display(df_q6)

                      Programa_de_TV  Temporadas
0                     Grey's Anatomy          20
1                   Naruto Shippuden          20
2                   Heartland (2007)          17
3  It's Always Sunny in Philadelphia          16
4                               NCIS          15

7.	¿Cuáles son los intervalos de fechas de los resúmenes en la tabla `view_summary` de los períodos (`duration`) semestrales?

In [45]:
from IPython.core.interactiveshell import dis
conn.rollback()
q7 = """
SELECT
  duration AS tipo_de_periodo,
  MIN(start_date) AS fecha_inicio,
  MAX(end_date) AS fecha_fin,
  COUNT(*) AS rows_in_summary
FROM view_summary
WHERE duration LIKE '%Semester%'
   OR duration LIKE '%semester%'
   OR duration LIKE '%Semi%'
   OR duration LIKE '%semi%'
GROUP BY duration
ORDER BY fecha_inicio
;
"""
df_q7 = run_query(q7)
display(df_q7)

  tipo_de_periodo fecha_inicio   fecha_fin  rows_in_summary
0   SEMI_ANNUALLY   2023-07-01  2024-06-30            31675

8.	Ordena las temporadas de *Grey's Anatomy* según la cantidad de vistas registradas en el primer período semestral de 2024.
* ¿Cómo interpretarías los resultados obtenidos?

In [48]:
q8 = """
SELECT
  s.season_number        AS temporada,
  SUM(vs.views)          AS total_vistas
FROM tv_show ts
JOIN season s
  ON ts.id = s.tv_show_id
JOIN view_summary vs
  ON s.id = vs.season_id
WHERE ts.title = "Grey's Anatomy"
  AND vs.duration LIKE '%Sem%'
  AND vs.start_date >= '2024-01-01'
  AND vs.end_date   <= '2024-06-30'
GROUP BY s.season_number
ORDER BY total_vistas DESC;
"""
df_q8 = run_query(q8).map('{:,.0f}'.format)
display(df_q8)

   temporada total_vistas
0          1    3,600,000
1          2    3,100,000
2          3    2,900,000
3          5    2,900,000
4          4    2,900,000
5          6    2,800,000
6          7    2,700,000
7          8    2,600,000
8          9    2,500,000
9         10    2,400,000
10        11    2,200,000
11        12    2,000,000
12        13    2,000,000
13        14    2,000,000
14        19    2,000,000
15        15    1,900,000
16        16    1,800,000
17        18    1,700,000
18        17    1,700,000
19        20      100,000

**texto en negrita**

**Análisis**
claramente la serie comenzó con un gran punch y perdio popularidas a partir de la 7ma a 9na temporada vs su inicio, sin embargo mantiene un publico cautivo constante, lo cual es sorprendente para una historia tan larga.

9.	Todas las consultas anteriores podrían hacerse también con la lógica relacional implementada en Pandas, que permite replicar la mayoría de las operaciones de SQL. Si los dataframes se han llenado como sigue, resuelve la consulta 8 utilizando las funciones de Pandas.

In [ ]:
tv_show = pd.read_sql(sqla.text('SELECT * FROM tv_show'), conn)
season = pd.read_sql(sqla.text('SELECT * FROM season'), conn)
view_summary = pd.read_sql(sqla.text('SELECT * FROM view_summary'), conn)

`MySQL` es un sistema de gestión de bases de datos relacional, pero desde Python también es posible extraer información de bases de datos no relacionales, como `Firestore`, `MongoDB` o `Cassandra`, utilizando conectores o integraciones específicas. Esto permite combinar datos de diferentes fuentes según las necesidades del análisis o la aplicación.

En el siguiente ejercicio usarás un ejemplo con `Firestore` desde Python. Para ello utilizarás los módulos `credentials` y `firestore` de la biblioteca `firebase_admin`.

In [ ]:
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

En `Firestore`, a diferencia de `MySQL` donde se utiliza un usuario y contraseña para conectarse, la autenticación se realiza mediante un archivo JSON que almacena las credenciales necesarias para acceder a la base de datos. Este archivo contiene las claves y la información de configuración que permiten a Python establecer la conexión de manera segura.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Debes descargar el archivo de credenciales "consultancy.json" (disponible en las instrucciones de Canvas) y ubicarte en la carpeta donde lo almacenaste
import os
DIR = "/content/drive/MyDrive/Colab Notebooks/MNA/TC5053 - Ciencia y analítica de datos/Actividad3_BD_Manipulacion"
os.chdir(DIR)

In [ ]:
# consultancy.json almacena la clave privada para autenticar una cuenta y autorizar el acceso a los servicios
# A través de la función Certificate(), se regresa una credencial inicializada, que puedes utilizar para crear una nueva instancia de la aplicación
cred = credentials.Certificate('consultancy.json')
firebase_admin.initialize_app(cred)
db = firestore.client()

10.	Investiga cómo leer la colección `EMPLOYEE` y mostrar su contenido en un dataframe. Asegúrate de incluir el `id` en el resultado

In [ ]:
firebase_admin.delete_app(firebase_admin.get_app())